{
  "hash": "daabc0fd85f6905b954f09eea5117dba",
  "result": {
    "engine": "knitr",
    "markdown": "---\npagetitle: \"Linear Regression III\"\neditor: source\nformat:\n  revealjs:\n    html-math-method: mathjax\n    chalkboard: true\n    incremental: true\n    theme: [default, custom.scss]\n    height: 900\n    width: 1600\n    slide-number: c\n    auto-stretch: false\n    callout-appearance: simple\n    pdf-max-pages-per-slide: 2\n    menu:\n      side: right\n      numbers: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n::::: columns\n::: {.column .center width=\"55%\"}\n![](img/tidymodels.png){width=\"90%\"}\n:::\n\n::: {.column .center width=\"45%\"}\n<br>\n\n[Linear Regression III]{.custom-title}\n\n<br> <br> <br> <br> <br> \n\n[Grayson White]{.custom-subtitle}\n\n[Stat 243 <br> Week 3 \\| Fall 2026]{.custom-subtitle}\n:::\n:::::\n\n------------------------------------------------------------------------\n\n\n\n## Goals for this week (and next time)\n\n:::: {.columns}\n\n::: {.column width='50%'}\n\n::: {.nonincremental .fragment}\n\n**Today:**\n\n-   Inference for regression\n-   Categorical predictors\n-   Multiple linear regression\n\n:::\n\n:::\n\n::: {.column width='50%'}\n\n::: {.nonincremental .fragment}\n\n**Next time:**\n\n-   Quiz on Lab 1 (20 mins)\n-   Linear regression extensions (30 mins)\n-   Lab 2 released\n\n\n:::\n\n:::\n\n::::\n\n\n\n# Inference for Linear Models\n\n## Statistical Inference\n\n- **Goal**: Use *statistics* calculated from data to make estimates about unknown *parameters*\n\n- **Parameters**: $\\beta_0$, $\\beta_1$\n\n- **Statistics**: $\\hat{\\beta}_0$, $\\hat{\\beta}_1$\n\n- **Tools**: confidence intervals, hypothesis tests\n\n- **The Problems**: Our model will change if built using a different random sample. So in addition to estimates, we need to know about variability\n\n\n\n\n## The Confidence Interval \n\n- Confidence Intervals give estimates **and** express an amount of uncertainty we have about those estimates\n\n::: {.fragment .nonincremental}\n\n- A $C$-level confidence interval for a parameter $\\theta$ using the statistic $\\hat{\\theta}$ takes the form\n\n$$\n\\hat{\\theta} \\pm t^*_C \\cdot \\widehat{\\mathrm{SE}}(\\hat{\\theta})\n$$\n\n:::\n\n\n- The value $t^*_C$ is the $1 - (1-C)/2$ quantile for the sampling distribution of $\\hat{\\theta}$\n    - i.e. if $\\hat{\\theta}$ is approximately Normally distributed and $C = .95$, then $t^*_C \\approx 2$.\n\n- The value $\\widehat{\\mathrm{SE}}(\\hat{\\theta})$ is the estimated standard error of $\\hat{\\theta}$, or the estimated standard deviation of the sampling distribution\n\n\n## Common Regression Assumptions\n\nIn order to use simple linear regression for inference, we require the **LINE** assumptions.\n\n:::{.nonincremental}\n1. **Linearity**: The relationship between explanatory and response variables must be approximately linear\n    \n2. **Independence**: The observations should be independent of one another.\n\n3. **Normality**: The distribution of residuals should be *approximately* bell-shaped, unimodal, symmetric, and centered at 0 at every \"slice\" of the explanatory variable\n\n4. **Equal Variability**: Variance of residuals should be roughly constant across data set. Also called \"homoscedasticity\". Models that violate this assumption are sometimes called \"heteroscedastic\"\n\n:::  \n\n::: {.fragment .fade-up .midi .center}\n\nIf one or more of these conditions do not hold, our predictions may not be accurate and we should be skeptical of inferential claims.\n\n:::\n\n## The Sampling Distribution of $\\hat{\\beta}_1$\n\nAssume the following true model:\n$$\nf(x) = 12 + 0.7  x; \\quad \\epsilon \\sim N(0, 4)\n$$\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nset.seed(145)\nn <- 60\nbeta_0 <- 12\nbeta_1 <- .7\nsigma <- 2\nx <- rnorm(n, mean = 20, sd = 3)\nf_mean <- beta_0 + beta_1*x\ny <- f_mean + rnorm(n, mean = 0, sd = sigma)\n\nmy_data <- data.frame(x,y)\n\nggplot(my_data,\n       aes(x = x, y = y)) + \n  geom_abline(slope = beta_1, \n              intercept = 12) +\n  geom_point(color = \"steelblue\") +\n  geom_abline(slope = beta_1, \n              intercept = 12,\n              color = \"goldenrod\",\n              size = 1) +\n  theme_bw() +\n  annotate(\"text\", x = 26, y = 29, label = \"f(x)\", color = \"goldenrod\",parse = T) +\n  labs(title = \"Simulated Data from true model\")\n```\n\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n:::\n\n## The Sampling Distribution of $\\hat{\\beta}_1$\n\nAssume the following true model:\n$$\nf(x) = 12 + 0.7  x; \\quad \\epsilon \\sim N(0, 4)\n$$\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nggplot(my_data, \n       aes(x = x, y = y)) +\n  geom_abline(slope = beta_1,\n              intercept = 12,\n              color = \"goldenrod\",\n              size = 1) +\n  geom_point(color = \"steelblue\")+\n  geom_smooth(method = \"lm\",\n              se = F,\n              color = \"black\") +\n  theme_bw() +\n  annotate(\"text\", x = 26, y = 29, label = \"f(x)\", color = \"goldenrod\", parse = T) +\n  annotate(\"text\", x = 26, y = 32.5, label = \"hat(f)(x)\", color = \"black\", parse = T) +\n  labs(title = \"Estimate for f based on 1 simulation\")\n```\n\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n## The Sampling Distribution of $\\hat{\\beta}_1$\n\nAssume the following true model:\n$$\nf(x) = 12 + 0.7  x; \\quad \\epsilon \\sim N(0, 4)\n$$\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nset.seed(1020)\nit <- 1000\nslope <- rep(NA, times = it)\nintercept <- rep(NA, times = it)\nfor(i in 1:it) {\n  x <- rnorm(n, mean = 20, sd = 3)\n  f_mean <- beta_0 + beta_1 * x\n  y <- f_mean + rnorm(n, mean = 0, sd = sigma)\n  slope[i] <- lm(y ~ x)$coef[[2]]\n  intercept[i] <- lm(y ~ x)$coef[[1]]\n}\nmany_mods <- data.frame(slope, intercept)\n\nggplot(my_data, \n       aes(x = x, y = y)) +\n  geom_point(color = \"steelblue\") +\n  geom_abline(data = many_mods, \n              slope = slope, \n              intercept = intercept, \n              alpha = .02) +\n  geom_smooth(method = \"lm\",\n              se = F,\n              color = \"black\") +\n  geom_abline(slope = beta_1,\n              intercept = 12,\n              color = \"goldenrod\",\n              size = 1) +\n  theme_bw() +\n  labs(title = \"Estimates for f based on 1000 simulations\")\n```\n\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## The Sampling Distribution of $\\hat{\\beta}_1$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## The Sampling Distribution of $\\hat{\\beta}_1$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## The Sampling Distribution of $\\hat{\\beta}_1$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## The Sampling Distribution of $\\hat{\\beta}_1$\n\nThe Sampling Distribution has the following characteristics:\n\n1. Centered at $\\beta_1$, i.e. $\\mathbb{E}(\\hat{\\beta}_1) = \\beta_1$.\n\n2. $\\mbox{Var}(\\hat{\\beta}_1) = \\frac{\\sigma^2}{S_{XX}}$.\n    - where $S_{XX} = \\sum_{i = 1}^n (x_i - \\bar{x})^2$\n  \n3. $\\hat{\\beta}_1 | X \\sim N (\\beta_1, \\frac{\\sigma^2}{S_{XX}})$.\n\n\n::: {.fragment .fade-up .midi .center}\n\n**Who cares?**\n\n:::\n\n- We need facts about the sampling distribution to do two main tasks:\n    - build confidence intervals, and\n    - perform hypothesis tests.\n\n\n## Building a confidence interval\n\nWe'd like to use the sampling distribution to build a CI for $\\beta$:\n\n$$\n\\hat{\\beta} \\pm t^*_C \\cdot \\widehat{\\mathrm{SE}}(\\hat{\\beta})\n$$\n\n- Our best estimate of $\\beta_1$ is $\\hat{\\beta}_1$ (since the expected value $\\hat \\beta_1$ is $\\beta_1$)\n\n- However, we need to estimate $\\mbox{SE}(\\hat\\beta)$. How to do this? \n\n- Use the sampling distribution!! (*Why can't we?*)\n\n- In reality we never have access to the true sampling distribution. Instead we approximate it by: \n    - Assuming it follows a distributional form, or\n    - Using simulation (e.g., the bootstrap)\n\n\n## Building a confidence interval for $\\hat{\\beta}_1$\n\n::: {.nonincremental}\n\n- In reality we never have access to the true sampling distribution. Instead we approximate it by: \n    - Assuming it follows a distributional form, or\n    - Using simulation (bootstrap)\n\n:::\n\n:::: {.columns}\n\n::: {.column}\n\n**Distributional assumptions**\n\n\n$$\\widehat{\\mbox{SE}}(\\hat{\\beta}_1) = \\frac{\\hat \\sigma}{\\sqrt{\\sum_{i=1}^n(x_i - \\bar x)^2}}$$\n\n\n- For linear regression, reasonable if we (1) meet the LINE conditions, and (2) have a sample size >30. \n\n:::\n\n::: {.column .fragment}\n\n\n**Simulation (bootstrap)**\n\nUse the percentile or standard error method to estimate $\\mbox{SE}(\\hat\\beta_1)$ from estimates of $\\beta_1$ from many bootstrap samples. \n\n- For linear regression, reasonable if we (1) meet Linearity and Independence, and (2) have a sample size >30. \n\n\n:::\n\n::::\n\n\n## Performing a hypothesis test for $\\hat{\\beta}_1$ \n\n\nSuppose we are interested in testing the claim that the slope is zero.\n\n$$\nH_0: \\beta_1 = 0 \\qquad \\textrm{vs} \\quad H_A: \\beta_1 \\ne 0\n$$\n\n- Two options: use **simulation** (permutation), or make **distributional assumptions**. \n\n\n\n:::: {.columns style=\"font-size: 0.75em;\"}\n\n::: {.column .fragment}\n\n**Distributional assumptions**\n\n\nConsider the statistic $t$ given by\n$$\nt = \\frac{\\hat{\\beta}_1}{\\widehat{\\mbox{SE}}(\\hat{\\beta}_1)}\n$$\n\n- $t \\sim t(\\mbox{df} = n-2)$ and $SE(\\hat{\\beta}_1)$ calculated the same as in the CI.\n\n- For linear regression, reasonable if we (1) meet the LINE conditions, and (2) have a sample size >30. \n\n:::\n\n::: {.column .fragment}\n\n\n**Simulation (permutation)**\n\nUse the percentile or standard error method to estimate $\\mbox{SE}(\\hat\\beta_1)$ from estimates of $\\beta_1$ from many permutations of your original dataset. \n\n- For linear regression, reasonable if we meet Linearity and Independence. No sample size restriction\n\n\n:::\n\n::::\n\n\n\n# Categorical Predictors\n\n------------------------------------------------------------------------\n\n### What About A Categorical Explanatory Variable?\n\n-   Response variable $(y)$: quantitative\n\n-   Have 1 categorical explanatory variable $(x)$ with two categories.\n\n-   Model form:\n\n::: fragment\n$$ \n\\begin{align}\ny &= \\beta_o + \\beta_1 x + \\epsilon\n\\end{align}\n$$\n:::\n\n-   First, need to convert the categories of $x$ to numbers.\n\n------------------------------------------------------------------------\n\n### Example: Halloween Candy\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncandy <- read_csv(\"https://raw.githubusercontent.com/fivethirtyeight/data/master/candy-power-ranking/candy-data.csv\")\nglimpse(candy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 85\nColumns: 13\n$ competitorname   <chr> \"100 Grand\", \"3 Musketeers\", \"One dime\", \"One quarter…\n$ chocolate        <dbl> 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…\n$ fruity           <dbl> 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,…\n$ caramel          <dbl> 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ peanutyalmondy   <dbl> 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ nougat           <dbl> 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…\n$ crispedricewafer <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ hard             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,…\n$ bar              <dbl> 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…\n$ pluribus         <dbl> 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,…\n$ sugarpercent     <dbl> 0.732, 0.604, 0.011, 0.011, 0.906, 0.465, 0.604, 0.31…\n$ pricepercent     <dbl> 0.860, 0.511, 0.116, 0.511, 0.511, 0.767, 0.767, 0.51…\n$ winpercent       <dbl> 66.97173, 67.60294, 32.26109, 46.11650, 52.34146, 50.…\n```\n\n\n:::\n:::\n\n\nWhat might be a good categorical explanatory variable of `winpercent`?\n\n------------------------------------------------------------------------\n\n### Exploratory Data Analysis\n\nBefore building the model, let's explore and visualize the data!\n\n-   What `dplyr` functions should I use to find the mean and sd of `winpercent` by the categories of `chocolate`?\n\n-   What graph should we use to visualize the `winpercent` scores by `chocolate`?\n\n------------------------------------------------------------------------\n\n### Exploratory Data Analysis\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Summarize\ncandy %>%\n  group_by(chocolate) %>%\n  summarize(count = n(),\n            mean_win = mean(winpercent), \n            sd_win = sd(winpercent))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  chocolate count mean_win sd_win\n      <dbl> <int>    <dbl>  <dbl>\n1         0    48     42.1   10.2\n2         1    37     60.9   12.8\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Exploratory Data Analysis\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nggplot(candy, aes(x = factor(chocolate), \n                   y = winpercent, \n                  fill = factor(chocolate))) +\n  geom_boxplot() +\n  stat_summary(fun = mean,\n               geom = \"point\",\n               color = \"yellow\",\n               size = 4) +\n  guides(fill = \"none\") +\n  scale_fill_manual(values =\n                      c(\"0\" = \"deeppink\",\n                        \"1\" = \"chocolate4\")) +\n  scale_x_discrete(labels = c(\"No\", \"Yes\"),\n                   name =\n          \"Does the candy contain chocolate?\")\n```\n\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n\n### Fit the Linear Regression Model\n\nModel Form:\n\n$$ \n\\begin{align}\ny &= \\beta_o + \\beta_1 x + \\epsilon\n\\end{align}\n$$\n\nWhen $x = 0$: [$\\qquad y = \\beta_o + \\epsilon$]{.fragment}\n\n<br>\n\nWhen $x = 1$: [$\\qquad y = \\beta_o + \\beta_1 + \\epsilon$]{.fragment}\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod <- lm(winpercent ~ chocolate, data = candy)\nlibrary(moderndive)\nget_regression_table(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term      estimate std_error statistic p_value lower_ci upper_ci\n  <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept     42.1      1.65     25.6        0     38.9     45.4\n2 chocolate     18.8      2.50      7.52       0     13.8     23.7\n```\n\n\n:::\n:::\n\n\n:::\n\n------------------------------------------------------------------------\n\n### Notes\n\n-   When the explanatory variable is categorical, $\\beta_o$ and $\\beta_1$ no longer represent the intercept and slope.\n\n-   Now $\\beta_o$ represents the (population) mean of the response variable when $x = 0$.\n\n-   And, $\\beta_1$ represents the change in the (population) mean response going from $x = 0$ to $x = 1$.\n\n-   Can also do prediction:\n\n::: fragment\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_candy <- data.frame(chocolate = c(0, 1))\npredict(mod, newdata = new_candy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1        2 \n42.14226 60.92153 \n```\n\n\n:::\n:::\n\n:::\n\n\n\n\n------------------------------------------------------------------------\n\n\n\n## New example: Palmer Penguins\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\n```\n:::\n\n\n\n\n![](img/penguins.png){fig-align=\"center\"}\n\n\n## Take a look at the data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel…\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse…\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, …\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, …\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186…\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, …\n$ sex               <fct> male, female, female, NA, female, male, female, male…\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…\n```\n\n\n:::\n:::\n\n\nWe'd like to predict a penguin's bill length based on their species.\n\n**Response variable**?\n\n**Explanatory variable**?\n\n## Exploratory data analysis\n\n:::: {.columns}\n\n::: {.column width=50%}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguins %>%\n  group_by(species) %>%\n  summarize(\n    avg_bill_length = mean(bill_length_mm,\n                           na.rm = TRUE)\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  species   avg_bill_length\n  <fct>               <dbl>\n1 Adelie               38.8\n2 Chinstrap            48.8\n3 Gentoo               47.5\n```\n\n\n:::\n:::\n\n\n:::\n\n:::{.column width=50%}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(penguins, \n       aes(x = species,\n           y = bill_length_mm, \n           fill = species)) +\n  geom_boxplot() +\n  scale_fill_manual(values = c(\"steelblue\",\n                               \"goldenrod\", \n                               \"plum3\")) +\n  guides(fill = \"none\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n:::\n\n::::\n\n:::{.fragment}\nHow do we handle more than 2 groups???\n:::\n\n\n# Boardwork\n\n------------------------------------------------------------------------\n\n\n## Fit the model in R\n\n:::{.fragment}\n$$\ny = \\beta_o + \\beta_1 x_{species:Chinstrap} + \\beta_2 x_{species:Gentoo} + \\epsilon\n$$\n:::\n\n:::{.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npenguin_mod <- lm(bill_length_mm ~ species, penguins)\nget_regression_table(penguin_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term               estimate std_error statistic p_value lower_ci upper_ci\n  <chr>                 <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept             38.8      0.241     161.        0    38.3     39.3 \n2 species: Chinstrap    10.0      0.432      23.2       0     9.19    10.9 \n3 species: Gentoo        8.71     0.36       24.2       0     8.01     9.42\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n\n:::{.fragment}\n\\begin{align*}\n\\hat{y} &= \\hat{\\beta}_o + \\hat{\\beta}_1 \\cdot x_{species:Chinstrap} + \\hat{\\beta}_2 \\cdot x_{species:Gentoo} \\\\\n &= 38.8 + 10.0 \\cdot x_{species:Chinstrap} + 8.71 \\cdot x_{species:Gentoo}\n\\end{align*}\n:::\n\n\n:::{.fragment}\nCoefficient interpretation?\n:::\n\n\n------------------------------------------------------------------------\n\n\n# Multiple Linear Regression\n\n------------------------------------------------------------------------\n\n### Before:\n\nWe predicted a penguin's bill length based on their species.\n\n::: {.fragment}\n\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = species, y = bill_length_mm, fill = species)) +\n  geom_boxplot() + \n  scale_fill_manual(values = c(\"steelblue\",\n                               \"goldenrod\", \n                               \"plum3\")) +\n  stat_summary(fun = mean, \n               geom = \"point\", \n               size = 3,\n               color = \"deeppink\") + \n  guides(fill = \"none\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n:::\n\n-   Pink dots represent the mean value in each group. \n-   For the single categorical variable model, those pink dots are the predicted values for each group. \n\n------------------------------------------------------------------------\n\n### Now: \n\nWe'll incorporate bill depth for prediction!\n\n::: {.fragment}\n\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) +\n  geom_point(size = 2) + \n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n:::\n\n-   A moderate negative relationship between bill length and bill depth! \n-   Does this make sense?\n\n------------------------------------------------------------------------\n\n![](img/culmen_depth.png){fig-align='center'}\n\n\n------------------------------------------------------------------------\n\n### What if we include both explanatory variables? \n\n::: {.fragment}\n\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +\n  geom_point(size = 2) + \n  geom_smooth(inherit.aes = FALSE, \n              mapping = aes(x = bill_depth_mm,\n                            y = bill_length_mm),\n              method = \"lm\",\n              se = FALSE,\n              color = \"red\") + \n  geom_parallel_slopes(se = FALSE) + \n  scale_color_manual(values = c(\"steelblue\",\n                               \"goldenrod\", \n                               \"plum3\")) +\n  theme_bw() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::\n\n-   **Negative** relationships between bill depth and bill length overall.\n-   **Positive** relationships between bill depth and bill length when accounting for species! \n-   **What is going on here??**\n-   This is a case of **Simpson's Paradox**. \n\n------------------------------------------------------------------------\n\n### Three candidate models\n\n:::: {.columns}\n\n::: {.column width=50%}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nspecies_mod <- lm(bill_length_mm ~ species, penguins)\nget_regression_table(species_mod) %>%\n  select(term, estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  term               estimate\n  <chr>                 <dbl>\n1 intercept             38.8 \n2 species: Chinstrap    10.0 \n3 species: Gentoo        8.71\n```\n\n\n:::\n:::\n\n\n<br>\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndepth_mod <- lm(bill_length_mm ~ bill_depth_mm, penguins)\nget_regression_table(depth_mod) %>%\n  select(term, estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  term          estimate\n  <chr>            <dbl>\n1 intercept        55.1 \n2 bill_depth_mm    -0.65\n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n\n::: {.column width=50%}\n\n<br>\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nboth_mod <- lm(bill_length_mm ~ bill_depth_mm + species, penguins)\nget_regression_table(both_mod) %>%\n  select(term, estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  term               estimate\n  <chr>                 <dbl>\n1 intercept             13.2 \n2 bill_depth_mm          1.39\n3 species: Chinstrap     9.94\n4 species: Gentoo       13.4 \n```\n\n\n:::\n:::\n\n\n:::\n\n:::\n\n::::\n\n-   **Coefficient interpretations**?\n\n------------------------------------------------------------------------\n\n### Interpreting the Multiple Regression Equation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nget_regression_table(both_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  term               estimate std_error statistic p_value lower_ci upper_ci\n  <chr>                 <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept             13.2      2.25       5.88       0     8.80    17.6 \n2 bill_depth_mm          1.39     0.122     11.4        0     1.15     1.63\n3 species: Chinstrap     9.94     0.368     27.0        0     9.22    10.7 \n4 species: Gentoo       13.4      0.512     26.2        0    12.4     14.4 \n```\n\n\n:::\n:::\n\n:::{.fragment}\n\n$$\n\\hat{y}= 13.2 + 1.39 \\cdot x_{\\textrm{Bill Depth}} + 9.94 \\cdot  x_{\\textrm{Species:Chinstrap}} + 13.4 \\cdot x_{\\textrm{Species:Gentoo}}\n$$\n\n:::\n\n-   **Slope Coefficient on Quantitative Variable:** The *expected/predicted* change in response variable, *on average*, per unit increase in the explanatory variable, *holding all other variables constant*.\n    -   Example: We expect a 1.394mm increase in bill length for every 1mm increase in bill depth, on average, after holding species constant.\n\n\n------------------------------------------------------------------------\n\n### Interpreting the Multiple Regression Equation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nget_regression_table(both_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  term               estimate std_error statistic p_value lower_ci upper_ci\n  <chr>                 <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept             13.2      2.25       5.88       0     8.80    17.6 \n2 bill_depth_mm          1.39     0.122     11.4        0     1.15     1.63\n3 species: Chinstrap     9.94     0.368     27.0        0     9.22    10.7 \n4 species: Gentoo       13.4      0.512     26.2        0    12.4     14.4 \n```\n\n\n:::\n:::\n\n\n\n$$\n\\hat{y}= 13.2 + 1.39 \\cdot x_{\\textrm{Bill Depth}} + 9.94 \\cdot  x_{\\textrm{Species:Chinstrap}} + 13.4 \\cdot x_{\\textrm{Species:Gentoo}}\n$$\n\n\n    \n-   **Intercept Coefficient:** The *expected/predicted* value of the response, *on average*, when all explanatory variables are *set to 0*.\n    -   What does setting species to 0 mean in this context?\n\n\n------------------------------------------------------------------------\n\n## Returning to our MLR model\n\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +\n  geom_point(size = 2) + \n  geom_parallel_slopes(se = FALSE) + \n  scale_color_manual(values = c(\"steelblue\",\n                               \"goldenrod\", \n                               \"plum3\")) +\n  theme_bw() \n```\n\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-26-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n**Are equal slopes a reasonable assumption here?**\n\n## Different Slopes Model\n\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +\n  geom_point(size = 2) + \n  geom_smooth(method = \"lm\", se = FALSE) + \n  scale_color_manual(values = c(\"steelblue\",\n                               \"goldenrod\", \n                               \"plum3\")) +\n  theme_bw() \n```\n\n::: {.cell-output-display}\n![](stat243_wk03wed_files/figure-revealjs/unnamed-chunk-27-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n-   **Equal slopes** models force the relationship between quantitative predictors and the response variable to be the same for each group in the model.\n\n-   In contrast, **different slopes** models allow for **different relationships** between quantitative predictors and the response variable for each group in the model. \n\n-   How can we allow our model to have different slopes? \n\n## Contrasting model forms\n\nRecall the equal slopes model:\n\n$$\ny = \\beta_o + \\beta_1 \\cdot x_{\\textrm{Bill Depth}} + \\beta_2 \\cdot  x_{\\textrm{Species:Chinstrap}} + \\beta_3 \\cdot x_{\\textrm{Species:Gentoo}} + \\epsilon\n$$\n\n<br>\n\n:::{.fragment}\n\nHow can we allow the slopes to vary? \n\n:::\n\n::: {.fragment}\n\n$$\ny = \\beta_o + \\beta_1 \\cdot x_{\\textrm{Bill Depth}} + \\beta_2 \\cdot  x_{\\textrm{Species:Chinstrap}} + \\beta_3 \\cdot x_{\\textrm{Species:Gentoo}} + \\\\\n\\beta_4 \\cdot x_{\\textrm{Bill Depth}} \\cdot x_{\\textrm{Species:Chinstrap}} + \\beta_5 \\cdot x_{\\textrm{Bill Depth}} \\cdot x_{\\textrm{Species:Gentoo}} + \\epsilon \n$$\n\n:::\n\n-   **Coefficient interpretation?**\n\n## Different Slopes Model in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsame_slope <- lm(bill_length_mm ~ bill_depth_mm + species, penguins)\n\ndiff_slope <- lm(bill_length_mm ~ bill_depth_mm * species, penguins)\n```\n:::\n\n\n:::{.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nget_regression_table(same_slope)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  term               estimate std_error statistic p_value lower_ci upper_ci\n  <chr>                 <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept             13.2      2.25       5.88       0     8.80    17.6 \n2 bill_depth_mm          1.39     0.122     11.4        0     1.15     1.63\n3 species: Chinstrap     9.94     0.368     27.0        0     9.22    10.7 \n4 species: Gentoo       13.4      0.512     26.2        0    12.4     14.4 \n```\n\n\n:::\n:::\n\n\n:::\n\n<br>\n\n:::{.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nget_regression_table(diff_slope)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  term                    estimate std_error statistic p_value lower_ci upper_ci\n  <chr>                      <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept                 23.1       3.02       7.65   0       17.1      29.0 \n2 bill_depth_mm              0.857     0.164      5.22   0        0.534     1.18\n3 species: Chinstrap        -9.64      5.72      -1.69   0.093  -20.9       1.60\n4 species: Gentoo           -5.84      4.54      -1.29   0.199  -14.8       3.08\n5 bill_depth_mm:speciesC…    1.06      0.31       3.44   0.001    0.455     1.68\n6 bill_depth_mm:speciesG…    1.16      0.279      4.17   0        0.615     1.71\n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n------------------------------------------------------------------------\n\n\n## How to assess which model is best? \n\n\n-   Train-test split, check which minimizes MSE, bias, MAE, ...\n\n\n\n\n\n\n\n",
    "supporting": [
      "stat243_wk03wed_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}