---
title: "Syllabus"
subtitle: |
  Stat 243: Statistical Learning \
  Reed College \ 
  Fall 2026
author: "Grayson White"
format:
  html: default
  pdf: default
editor: 
  mode: source
---

## Useful Information

**Instructor**: Grayson White (he/him) 

-   Email: [gwhite@reed.edu](mailto:gwhite@reed.edu)
-   Office: Library 386
-   Office hours: Available [here](office_hours.qmd). 


**Links and course resources**:

The course website, [stat-243-f26.github.io](https://stat-243-f26.github.io/), includes information on the course, lecture slides, public course materials, and links to all other course resources:

-   Slack, for course correspondence,
-   Gradescope, for turning in (most) assignments, and
-   the RStudio Server.


**Meeting Times**:

We'll have a lecture-style meeting twice a week. **Attendance is required** (please see the *Participation and Attendance* section of the syllabus. 

-   Class is on Mondays, Wednesdays, and Fridays 11:00am - 11:50am, Library Room 389.




## Learning Outcomes

By the end of the course, you will be able to:

- Articulate and compare the different philosophical approaches to the three primary statistical tasks: estimation, prediction, and inference.
- Create valid statistical models, perform reproducible data analysis using software, and communicate results in technical and non-technical language in order to answer a specific research question.
- Assess and compare the performance of statistical models to real-world data, and select appropriate models according to suitable criteria.
- Justify and describe properties of statistical learning methods by appealing to mathematical theory.
- Use `R` to develop a reproducible workflow of data management, graphics, and statistical analyses.
- Be aware of ethical issues in statistics, and articulate how the improper use of statistical techniques can misinform and mislead others.


## Learning Materials & Tools

**Textbooks**: This class will primarily use the textbook, [An Introduction to Statistical Learning in R (ISLR)](https://www.statlearning.com), 2nd Edition by James, Witten, Hastie, and Tibshirani. It is available free online.

Additionally, we will rely on the textbook, [Beyond Multiple Linear Regression: Applied Generalized Linear Models and Multilevel Models in R](https://bookdown.org/roback/bookdown-BeyondMLR/), 2021 version by Roback and Legler. It is available free online.

**Technologies (R, Positron or RStudio, and Quarto)**: R is a free and open source programming language, Positron and RStudio are Integrated Development Environments (IDEs) which allows for streamlined use of the R programming language, and Quarto is a markdown language that allows for reproducible documents that include R code, text, images, and much more! Access to these resources is available locally on your own machine, or on the [RStudio Server](https://www.rstudio.reed.edu) for this course. A laptop that can access the internet is required for this course.

**Please let me know ASAP if you do not have access to a personal computer!**





## Assignments, Activities, and Projects

We'll have a few types of assignments, activities, and projects for this course. In particular: 

-   **Labs**:
    - Most weeks, we will have a lab. Most labs will be assigned on Friday in class and will be due the following week on Friday before class. 
    - Labs will be turned in via Gradescope. 
    - To help with various circumstances (expected and unexpected), you have up to 4 additional extensions days that you can use as you need (e.g., 1 additional day for 4 labs, 4 additional days for 1 lab, ...) but the extension days must be rounded up to the nearest day (e.g., 2 extra hours = 1 extension day). There is no need to notify me of your use of extension days. 
        - Note: if you use more than your allotted extension days for a lab in and, no credit will be received for that lab (e.g., if you have already used 3 extension days, and then turn in a lab 2 days late, you will receive 0 credit for that lab). 
        
-   **Lab Quizzes**:
    - We will have a short quiz in class on each lab the day it is due. 
    
-   **In-class activities**:
    - During lecture, we will include some in-class activities. Including but not limited to: 
        - group activities,
        - independent activities.
    
-   **Project**:
    - We'll have a final project for this course. There will be a presentation of the final project, and a written component.
    - No late projects are accepted.
    
-   **Exam**:
    - We'll have a final exam for this course. The exam will occur during finals week. 
    
## Participation and Attendance

Attending class and actively engaging with the content and activities in class is crucial to your own and your classmates learning. This is especially true in Stat 243: Statistical Learning, as much of the learning will happen through **active learning**. Because of this, I will be taking attendance at each class time and noting participation in class and in Slack. 

## Distribution Requirements

This course can be used towards your **Group III, “Natural, Mathematical, and Psychological Science”** requirement. It accomplishes the following learning goals for the group:

1. Use and evaluate quantitative data or modeling, or use logical/mathematical reasoning to evaluate, test or prove statements.
2. Given a problem or question, formulate a hypothesis or conjecture, and design an experiment, collect data or use mathematical reasoning to test or validate it.
3. Collect, analyze, and interpret data.

This course does **not** satisfy the "primary data collection and analysis" requirement.



## Course Climate

We expect everyone in this class to strive to foster a learning environment that is equitable, inclusive, and welcoming. If you experience any barriers to learning, please come to Professor Grayson White or a college administrator with your concerns.

**Code of Conduct**:

We expect all members of Stat 243 to make participation a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

We expect everyone to act and interact in ways that contribute to an open, welcoming, inclusive, and healthy community of learners. You can contribute to a positive learning environment by demonstrating empathy and kindness, being respectful of differing viewpoints and experiences, and giving and gracefully accepting constructive feedback.[^1]

[^1]: This Code of Conduct is adapted from the [Contributor Covenant](https://www.contributor-covenant.org/version/2/0/code_of_conduct.html), version 2.0.



## Policies

**Late work policy**:

Please see the late work policy for each individual assignment type that is included in the *Assignments, Activities, and Projects* section of the syllabus. 

**Collaboration Policy and Academic Honesty**:

Working with your classmates on difficult and interesting problems can not only help your learning, but also help you get to know each other! Therefore, I encourage you to collaborate on assignments but **every piece of work you submit must be your own**. Copying and pasting other people’s work or code is not acceptable. The Honor Principle must guide your conduct in this class. Failure to act with academic integrity may result in failing the course. 

If you choose to collaborate with a classmate, **you must add their name to the top of your assignment**, and list them as a collaborator, e.g.:

Collaborator(s): Elliot Shannon, Romain Boutelet

*But what is collaboration?*:

For Stat 243, collaboration can look like: working with classmates together on a given problem, doing scratch work, helping each other get un-stuck on a part of a problem, and even coming to a solution. However, you **must** write up your own problem solutions individually and cannot copy other's solutions (even those who you have collaborated with). Further, copying code or solutions from a collaborator, classmate, or generative AI tool (see the following section) is strictly prohibited. 


**AI Policy**:

Artificial intelligence (AI) tools, such as ChatGPT, Claude, Co-Pilot, Gemini, and others are being used to generate code, analyze data, write, and much more (and they are getting quite good at many of these tasks!). However, learning to think critically about a problem at hand, and engaging with your peers, tutors, and instructors when not understanding a concept or question are integral components of a liberal arts education and goals of this course. Therefore, 

**For all course content**: The use of generative AI tools, such as ChatGPT and others, are strictly prohibited in any stage of the work process for this course.



