{
  "hash": "40e2dbdb0682fa3f6b902076b6217c23",
  "result": {
    "engine": "knitr",
    "markdown": "---\npagetitle: \"Linear Regression: Review\"\neditor: source\nformat:\n  revealjs:\n    html-math-method: mathjax\n    chalkboard: true\n    incremental: true\n    theme: [default, custom.scss]\n    height: 900\n    width: 1600\n    slide-number: c\n    auto-stretch: false\n    callout-appearance: simple\n    pdf-max-pages-per-slide: 2\n    menu:\n      side: right\n      numbers: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n::: {.center}\n\n<br> <br> <br>\n\n[Linear Regression: Review]{.custom-title}\n\n<br> <br>\n\n[Michael Pearce]{.custom-subtitle}\n\n[Math 243]{.custom-subtitle}\n\n:::\n\n------------------------------------------------------------------------\n\n## Outline\n\n::: {.nonincremental}\n\nIn today's class, we will...\n\n- Review simple and multiple linear regression\n\n- Perform inference for linear regression models\n\n- Implement linear regression in `R`\n\n:::\n\n# Foundations\n\n## Linear Regression\n\nSuppose we have:\n\n::: {.nonincremental}\n\n  - one or more **predictors**,  $(X_1, X_2, \\dots , X_p)$\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - a **quantitative response variable** $Y$, where\n\n$$\nY = f(X_1, \\dots, X_p) + \\epsilon\n$$\nwhere $\\epsilon$ (\"epsilon\") is random \"error\" or \"noise\"\n\n:::\n\n::: {.fragment .nonincremental}\n\nThe **simplest form** for $f$ is a **linear function**:\n$$\nf(x_1, x_2, \\dots , x_p) = \\beta_0 + \\beta_1 x_1 + \\dots + \\beta_p x_p\n$$\n\n:::\n\n::: {.fragment .nonincremental}\n\nIf $Y$ depends on..\n\n  - 1 predictor, $X$, we have **Simple Linear Regression** (SLR)\n\n  - $\\geq2$ predictors, $X_1,\\dots,X_p$, we have **Multiple Linear Regression** (MLR)\n\n:::\n\n## Approximations and Estimates\n\n**The relationship $f$ between $Y$ and $X_1, \\dots, X_p$ is rarely linear!**\n\n::: {.fragment .nonincremental}\n\n  - linear models are still good approximations, often\n\n:::\n\n::: {.fragment .nonincremental}\n\n**Problem:** Even if $f$ is linear, we still do not know its parameters\n\n:::\n\n::: {.fragment .nonincremental}\n\n- **Solution:** Using data, we estimate the parameters and the model:\n$$\n\\hat{f} (x_1, \\dots, x_p) = \\hat{\\beta}_0 + \\hat{\\beta}_1 x_1 + \\dots + \\hat{\\beta}_px_p\n$$\n\n- $\\hat{\\beta_k}$ are *estimates* of the \"true\" $\\beta_k$\n- Obtain $\\hat{\\beta_k}$ via **least-squares**: Values of $\\hat{\\beta_k}$ that minimize the total squared distance between data and the regression line,\n$$\\sum_{i=1}^n \\Big(y_i - \\hat{f}(x_{1i},\\dots,x_{pi})\\Big)^2$$\n\n:::\n\n::: {.fragment .nonincremental}\n\nIf $f$ is NOT linear, then:\n\n- we're estimating an *approximation* of the relationship between $Y$ and $X_1, \\dots, X_p$\n\n:::\n\n## Categorical Predictors\n\nIt's most common to have quantitative predictor variables, but categorical (i.e. qualitative) predictors are also common.\n\n::: {.nonincremental}\n\n  + Example: Penguin species (Adelie, Gentoo, Chinstrap)\n  + Example: State of residence (Oregon, Washington, etc.)\n\n:::\n\n::: {.fragment .nonincremental}\n\nUnfortunately, we can't directly add categorical variables to regression equations, since **can't perform algebra** with them!\n\nFor example, consider the following regression model:\n$$\\hat{\\text{Income}} = 30{,}000 + 5{,}000\\times\\text{Oregon}$$\nWhat is $5{,}000\\times\\text{Oregon}$?!\n\n:::\n\n## Categorical Predictors: Indicator Variables\n\nTo perform algebra with categories, we usually convert each **level** of a categorical variable into an **indicator variable** (denoted with letter $I$):\n$$I\\{\\text{Oregon}\\} = \\begin{cases} 1 & \\text{if } X = \\text{Oregon} \\\\ 0 & \\text{otherwise} \\end{cases}$$\n\n::: {.fragment .nonincremental}\n\nReturning to our example on the previous slide, we now have\n$$\\begin{aligned}\n\\hat{\\text{Income}} &= 30 + 5I\\{\\text{Oregon}\\} \\\\\n&=\\begin{cases} 30+5(1) & \\text{if } X=\\text{Oregon}\\\\\n30+ 5(0) & \\text{otherwise} \\end{cases}\n\\end{aligned}$$\n\n:::\n\n## Categorical Predictors: Number of Indicator Variables\n\nWhen converting a single categorical predictor into indicator variable(s), there is always **1 fewer indicator variable than there are levels**.\n\n::: {.fragment .nonincremental}\n\n**Example:** Suppose $X=\\text{Heads or Tails}$ (2 levels $\\implies$ 1 indicator variable):\n\n$$I\\{Heads\\} = \\begin{cases} 1 & \\text{if } X=\\text{Heads}\\\\\n                             0 & \\text{if } X=\\text{Tails} \\end{cases}$$\n\n:::\n\n::: {.fragment .nonincremental}\n\n**Example:** Suppose $X=\\text{Blue, Green, or Yellow}$ (3 levels $\\implies$ 2 indicator variables):\n\n$$I\\{Blue\\} = \\begin{cases} 1 & \\text{if } X=\\text{Blue}\\\\\n                             0 & \\text{if } X=\\text{Green or Yellow} \\end{cases}$$\n$$I\\{Green\\} = \\begin{cases} 1 & \\text{if } X=\\text{Green}\\\\\n                             0 & \\text{if } X=\\text{Blue or Yellow} \\end{cases}$$\n$\\implies$ if $I\\{Blue\\}=I\\{Green\\}=0$, then $X$ must be Yellow!\n\n:::\n\n## Example\n\nSuppose we model Income ($Y$) vs Age ($X_1$) and State $X_2\\in\\{OR, WA, CA\\}$\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n:::\n\n::: {.fragment}\n\n$$\\hat{\\text{Income}} = \\beta_0 + \\beta_1\\text{Age} + \\beta_2 I\\{\\text{OR}\\} + \\beta_3 I\\{\\text{WA}\\}$$\n\n:::\n\n::: {.fragment}\n\n$$\\begin{cases} \\beta_0+\\beta_1\\text{Age} & \\text{if State=CA}\\\\\n(\\beta_0+\\beta_2)+\\beta_1\\text{Age} & \\text{if State=OR}\\\\\n(\\beta_0+\\beta_3)+\\beta_1\\text{Age} & \\text{if State=WA}\n\\end{cases}$$\n\n:::\n\n# Interpretation\n\n## Coefficient Interpretation\n\nSuppose we estimate a linear regression model, $\\hat{f}$:\n\n$$\n\\hat{f} (x_1, \\dots, x_p) = \\hat{\\beta}_0 + \\hat{\\beta}_1 x_1 + \\dots + \\hat{\\beta}_px_p\n$$\n\nHow do we interpret the coefficients?\n\n::: {.fragment .nonincremental}\n\n  - Interpretation of coefficients is an **essential** statistical skill\n\n  - Don't be creative here! **Careful and precise** interpretation is necessary.\n\n  - Always include **context**: Relate interpretations to the actual data/variables studied.\n\n:::\n\n## Coefficient Interpretation (SLR)\n\nWe start with simple linear regression:\n$$\n\\hat{f} (x_1) = \\hat{\\beta}_0 + \\hat{\\beta_1} x_1\n$$\n\n::: {.nonincremental}\n\n  - **Intercept, $\\hat{\\beta_0}$**: When $x_1=0$, we expect $Y$ to be $\\hat{\\beta_0}$, on average.\n\n$$\\begin{aligned}\n\\text{Why?  }\\quad \\hat{f} (x_1=0) &= \\hat{\\beta}_0 + \\hat{\\beta_1}(0)\\\\\n&=\\hat\\beta_0\n\\end{aligned}$$\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - **Slope, $\\hat{\\beta_1}$**: For every one-unit increase in $x_1$, we expect $Y$ to change by $\\hat{\\beta_1}$, on average.\n\n$$\\begin{aligned}\n\\text{Why?  }\\quad \\hat{f} (x_1+1) -\\hat{f} (x_1) &= \\Big(\\hat{\\beta}_0 + \\hat{\\beta_1}(x_1+1)\\Big) - \\Big(\\hat{\\beta}_0 + \\hat{\\beta_1}(x_1)\\Big)\\\\\n&=\\hat\\beta_1\n\\end{aligned}$$\n\n:::\n\n## Coefficient Interpretation (MLR)\n\nWhat about MLR?\n$$\n\\hat{f} (x_1,\\dots,x_p) = \\hat{\\beta}_0 + \\hat{\\beta_1} x_1 + \\dots + \\hat{\\beta_p} x_p\n$$\n\n::: {.nonincremental}\n\n  - **Intercept, $\\hat{\\beta_0}$**: When $x_1=x_2=\\dots=x_p=0$, we expect $Y$ to be $\\hat{\\beta_0}$, on average.\n\n$$\\begin{aligned}\n\\text{Why?  }\\quad \\hat{f} (x_1=x_2=\\dots=x_p=0) &= \\hat{\\beta}_0 + \\hat{\\beta_1}(0)+\\dots+\\hat{\\beta_p}(0)\\\\\n&=\\hat\\beta_0\n\\end{aligned}$$\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - **Slope, $\\hat{\\beta_j}$**: For every one-unit increase in $x_j$, we expect $Y$ to change by $\\hat{\\beta_j}$, on average, holding all else constant.\n\n$$\\begin{aligned}\n\\text{Why?  }\\quad \\hat{f} (x_1+1) -\\hat{f} (x_1) &= \\Big(\\hat{\\beta}_0 + \\hat{\\beta_1}(x_1+1)\\Big) - \\Big(\\hat{\\beta}_0 + \\hat{\\beta_1}(x_1)\\Big)\\\\\n&=\\hat\\beta_1\n\\end{aligned}$$\n\n:::\n\n## Word of Caution: Categorical Variables\n\nSuppose we have the model\n$$\n  \\hat{Income} = \\beta_0 + \\beta_1Age + \\beta_2 I\\{State=\\text{Oregon}\\}\n$$\nwhere $Age$ is a quantitative variable and $State\\in\\{\\text{Oregon,Washington}\\}$\n\n::: {.fragment .nonincremental}\n\nInterpretations:\n\n+ $\\beta_0$: Expected $Income$ when $Age=0$ and State=Washington (the **baseline level**) on average.\n\n:::\n\n::: {.fragment .nonincremental}\n\n+ $\\beta_1$: Precisely as usual!\n\n:::\n\n::: {.fragment .nonincremental}\n\n+ $\\beta_2$: Comparing someone from Oregon to someone from Washington (the baseline), we expect Income to change by $\\beta_2$ on average, holding Age constant.\n\n:::\n\n## Other Advice\n\n::: {.nonincremental}\n\nAlways, always, always...\n\n1. Include the phrases \"on average\" and \"expected\" in your interpretations. If they aren't there, it's **wrong!**\n\n2. If there are **multiple variables** in your model, include the phrase \"holding all else constant\" (or something very similar contextual)\n\n3. Include **context**, not mathematical symbols\n\n:::\n\n# Statistical Inference in Regression\n\n## Conditions for Using Linear Regression\n\n**In *traditional* regression analyses, we must satisfy certain conditions:**\n\n::: {.fragment .nonincremental}\n\n1. **Linearity:** The relationship between predictor and response variables must be approximately linear\n\n    - Check using scatterplot/residual plot\n\n:::\n\n::: {.fragment .nonincremental}\n\n2. **Independence:** The observations should be independent of one another.\n\n    - Often \"contextual\"; sometimes can be seen in scatterplot/residual plot\n\n:::\n\n::: {.fragment .nonincremental}\n\n3. **Normality:** The distribution of residuals should be normally distributed, and centered at 0 **at every \"slice\" of the predictor variable**\n\n    - Histogram of residuals\n\n    - Q-Q plot of residuals\n\n:::\n\n::: {.fragment .nonincremental}\n\n4. **Equal Variability:** Variance of residuals should be roughly constant across data set.\n\n    - Check using residual plot.\n\n:::\n\n::: {.fragment}\n\nAbbreviated using acronym **LINE**\n\n:::\n\n## 1) Linearity\n\n**Linearity:** The relationship between $X$ and $Y$ must be approximately linear\n\n::: {.nonincremental}\n\n  - Points should be evenly distributed above and below the regression line **at each \"slice\" of X**\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - **Mathematically:** $Y = \\beta_0 + \\beta_1 X + \\epsilon$ where $E(\\epsilon \\ | \\ X) = 0$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\nIf data is non-linear...\n\n  - Slope does not adequately describe relationship\n\n  - Predictions can be very inaccurate\n\n:::\n\n## 1) Linearity\n\nLooking at residual plots is also very useful when checking this!\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## 2) Independent Observations\n\n**Independence:** The observations should be independent of one another (given $X$)\n\n::: {.fragment .nonincremental}\n\n  - **Mathematically:** $\\epsilon_i$ and $\\epsilon_j$ are independent (given $X$)\n\n:::\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n:::\n\n::: {.fragment .nonincremental}\n\nIf observations are not independent...\n\n  - Slope and intercept estimates may be more variable in sample\n\n  - Inference about the population may be misleading\n\n:::\n\n## 3) Normality (of Residuals)\n\n**Normality of Residuals:** The distribution of residuals should be normally distributed and centered at 0 **at every \"slice\" of $X$**\n\n::: {.fragment .nonincremental}\n\n- **Mathematically:** $\\epsilon \\ | \\ X \\sim N(0, \\sigma^2)$\n\n:::\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n:::\n\n::: {.fragment .nonincremental}\n\nIf residuals are non-Normal...\n\n  - Some predictions can be very inaccurate\n\n  - Inference about the population may be misleading\n\n:::\n\n## 4) Equal Variability (of Residuals)\n\n**Equal Variability:** Variance of residuals should be roughly constant across data set.\n\n::: {.nonincremental}\n\n- **Mathematically:** $var(\\epsilon \\ | \\ X) = \\sigma^2$ for constant $\\sigma^2$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n:::\n\n::: {.fragment .nonincremental}\n\nIf residuals don't have equal variability...\n\n  - Inference about the population may be misleading\n\n  - (Potential) outliers in high-variability range are more influential\n\n:::\n\n::: {.notes}\nResidual plots are also useful for checking this!\n:::\n\n## 4) Equal Variability (of Residuals)\n\n**Equal Variability:** Variance of residuals should be roughly constant across data set.\n\n::: {.nonincremental}\n\n- **Mathematically:** $var(\\epsilon \\ | \\ X) = \\sigma^2$ for constant $\\sigma^2$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\nIf residuals don't have equal variability...\n\n  - Inference about the population may be misleading\n\n  - (Potential) outliers in high-variability range are more influential\n\nResidual plots are also useful for checking this!\n\n:::\n\n## Statistical Inference\n\nWith a fitted linear model, we want to make **inferences**.\n\n::: {.fragment .nonincremental}\n\n**Our Question:** Learn about a **parameter** that summarizes a **population**\n\n  - e.g., $\\beta_0$ is \"true\" average $Y$ when $X_1=\\dots=X_p=0$\n\n:::\n\n::: {.fragment .nonincremental}\n\n**Solution:** Estimate a **statistic** from our **sample**\n\n  - e.g., fitted $\\hat{\\beta_0}$ is a good guess for $\\beta_0$\n\n  - We don't know \"how good\" an estimate $\\hat{\\beta_0}$ is!\n\n:::\n\n::: {.fragment .nonincremental}\n\n**Tools:**\n\n  - Confidence intervals\n\n  - Hypothesis tests\n\n:::\n\n::: {.fragment}\n\nBoth require us learn the statistic's **sampling distribution**\n\n:::\n\n## Sampling Distribution\n\n**Sampling Distribution:** the distribution of our statistic *across different random samples* (hypothetically)\n\n::: {.fragment .nonincremental}\n\n**Ex:** Estimating the Mean GPA of Reed students\n\n  - **Parameter:** Mean GPA of All Reed students\n\n  - **Statistic:** Mean GPA of a sample of 50 Reed students\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n:::\n\n:::: {.columns}\n\n::: {.column width=\"49%\"}\n\n::: {.fragment fragment-index=\"2\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n:::\n\n::: {.column width=\"49%\"}\n\n::: {.fragment fragment-index=\"3\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n:::\n\n::::\n\n::: {.fragment fragment-index=\"3\"}\n\n**Standard Error:** the standard deviation of the sample distribution\n\n:::\n\n## Confidence Intervals\n\n**Confidence Intervals** give estimates **and** express our uncertainty in those estimates.\n\n::: {.fragment .nonincremental}\n\nA $C$-level (e.g., 0.95-level or 95%) confidence interval for a **parameter $\\beta_j$** using the **statistic $\\hat{\\beta_j}$** means...\n\n  - In $C$% of random samples, the true $\\beta_j$ will be contained in the interval.\n\n  - **NOT** a C% \"chance\" that $\\beta_j$ is in the interval.\n\n:::\n\n::: {.fragment .nonincremental}\n\nTypically create intervals in two ways:\n\n1) Bootstrap method **← will review this in a later lecture**\n\n:::\n\n::: {.fragment .nonincremental}\n\n2) Theory-based inference\n\n    - Find sampling distribution using statistical theory (like Central Limit Theorem)\n\n    - Middle $C$% constitutes a proper confidence interval\n\n:::\n\n## Hypothesis Tests (Steps 1-3 of 5)\n\nA formal statistical process of testing hypotheses about a **parameter ($\\beta_j$)**\n\n::: {.fragment .nonincremental}\n\n1. **Present research question and identify Hypotheses**\n\n    - Null Hypothesis ($H_0$): $\\beta_j = \\gamma$ for some $\\gamma$\n\n    - Alternative Hypothesis ($H_A$): $\\beta_j > \\gamma$ or $\\beta_j < \\gamma$ or $\\beta_j \\neq \\gamma$\n\n:::\n\n::: {.fragment .nonincremental}\n\n2. **Choose a Test Statistic ($T$)**\n\n    - Usually a function of our statistic ($\\hat{\\beta_j}$)\n\n    - e.g., turning our statistic into something that *looks like* a z-score:\n$$\n  T = \\frac{\\hat{\\beta_j} - \\gamma}{\\mathrm{SE}(\\hat{\\beta_j})}\n$$\n\n    - We observe $T = t$\n\n:::\n\n::: {.fragment .nonincremental}\n\n3. **Determine the null (sampling) distribution of $T$**\n\n    - Theory-based inference tools, here!\n\n:::\n\n## Hypothesis Tests (Steps 4-5)\n\n::: {.nonincremental}\n\n1. Present research question and identify **Hypotheses ($H_0$ and $H_A$)**\n\n2. Choose a **Test Statistic ($T$)**\n\n3. Determine the **null (sampling) distribution** of $T$\n\n:::\n\n::: {.fragment .nonincremental}\n\n4. **Calculate the p-Value**:\n\n::: {.center}\n  p-Value: probability of what happened in reality (or something more extreme), assuming that the null is true.\n:::\n\n:::\n\n::: {.fragment .nonincremental}\n\n5. **Use the P-Value to make a conclusion on the research question**\n\n    - **Traditional:** \"Reject\" $H_0$ if $p<\\alpha$, a **significance level**; \"fail to reject $H_0$\" otherwise.\n\n    - **Modern (Better!):** $p$ provides **\"strength of evidence\"** against $H_0$.\n\n    - e.g., $p=0.001$ provides strong evidence that $H_0$ isn't true!\n\n:::\n\n## Statistical Inference in Regression\n\n**Parameters:**\n\n::: {.nonincremental}\n\n  - Assume there is a linear relationship between $Y$ and $X$:\n\\begin{align*}\n  Y = \\beta_0 + \\beta_1 X + \\epsilon\n\\end{align*}\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - **$\\beta_0$, $\\beta_1$ are the parameters!**\n\n**Q:** In words, what does it mean if $\\beta_1 = 0$? How about it $\\beta_1 \\neq 0$?\n\n:::\n\n::: {.fragment .nonincremental}\n\n**Statistics:** **$\\hat{\\beta}_0$, $\\hat{\\beta}_1$** estimated from our sample data!\n\n  - For theory-based inference, model must satisfy all LINE conditions\n\n  - Use `R` to perform confidence intervals or conduct hypothesis tests.\n\n:::\n\n## `R` code\n\nConsider the following regression between High School Graduate Rate ($Y$) and Poverty Rates ($X$):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod <- lm(Graduates ~ Poverty, data = poverty)\nget_regression_table(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term      estimate std_error statistic p_value lower_ci upper_ci\n  <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept   96.2       1.34      71.6        0    93.5    98.9  \n2 Poverty     -0.898     0.114     -7.86       0    -1.13   -0.668\n```\n\n\n:::\n:::\n\n\n::: {.fragment .nonincremental}\n\n**Hypothesis Test for $\\beta_1$**\n\n- `std_error` (0.114) and `statistic` (-7.86)\n\n- `p_value` --- corresponding p-value ($\\approx 0$) for the *two-sided test*,\n$$H_0: \\beta_1 = 0 \\qquad H_a: \\beta_1 \\neq 0$$\n\n:::\n\n## `R` code\n\nConsider the following regression between High School Graduate Rate ($Y$) and Poverty Rates ($X$):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod <- lm(Graduates ~ Poverty, data = poverty)\nget_regression_table(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term      estimate std_error statistic p_value lower_ci upper_ci\n  <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept   96.2       1.34      71.6        0    93.5    98.9  \n2 Poverty     -0.898     0.114     -7.86       0    -1.13   -0.668\n```\n\n\n:::\n:::\n\n\n**95% Confidence Interval**\n\n- 95% CI for $\\beta_1$ is (`lower_ci`,`upper_ci`)=(-1.13,-0.668)\n\n# Case Study\n\n## Credit Card Debt\n\nThe `Credit` dataset in the `ISLR` package contains (fabricated) credit card debt and other financial and demographic information for 400 individuals.\n\n::: {.fragment}\n\n**Goal:** Build a model that predicts credit debt given financial and demographic information\n\n:::\n\n::: {.fragment .nonincremental}\n\n- Consider Debt (`Balance`) as a function of Credit Limit (`Limit`) and Income in \\$1000 (`Income`)\n\n:::\n\n::: {.fragment}\n\n:::: {.columns}\n\n::: {.column width=\"45%\" .smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n$$R = 0.86 \\qquad \\widehat{Debt} = -292.8 + 0.17 \\cdot \\textrm{Limit}$$\n\n:::\n\n::: {.column width=\"45%\" .smaller}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n$$R = 0.46 \\qquad \\widehat{Debt} = 246.51 + 6.048 \\cdot \\textrm{Income}$$\n\n:::\n\n::::\n\n:::\n\n::: {.fragment}\n\nBoth predictors have some explanatory power for Debt -- and **positive correlations**\n\n:::\n\n## Multiple Regression for Debt\n\nLet's find the MLR model:\n\n::: {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod<-lm(Balance ~ Limit + Income, data = Credit)\nget_regression_table(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term      estimate std_error statistic p_value lower_ci upper_ci\n  <chr>        <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept -385.       19.5       -19.8       0 -423.    -347.   \n2 Limit        0.264     0.006      45.0       0    0.253    0.276\n3 Income      -7.66      0.385     -19.9       0   -8.42    -6.91 \n```\n\n\n:::\n:::\n\n\n:::\n\n$$\\widehat{Debt} = -385.179 + 0.264 \\cdot \\textrm{Limit} - 7.663 \\cdot \\textrm{Income}$$\n\n::: {.fragment .nonincremental}\n\n- For an individual with a $\\$0$ credit limit and no income, we expect $-\\$385$ in Debt, on average. (*nonsensical*)\n\n:::\n\n::: {.fragment .nonincremental}\n\n- As Credit Limit increases by $\\$1$, Debt is expected to **increase** by $\\$0.26$, on average, *holding Income fixed*\n\n:::\n\n::: {.fragment .nonincremental}\n\n- As Income increases by $\\$1000$, Debt is expected to **decrease** by $\\$7.66$, on average, *holding Credit Limit fixed*\n\nWait...**the coefficient on Income switched direction!! How?**\n\n:::\n\n## Income and Credit Limit\n\nFirst let's consider the relationship between Income and Credit Limit\n\n::: {.fragment .nonincremental}\n\n  - Remember that Credit Limit was more correlated with Debt than Income was ($R = 0.86$ vs. $R = 0.46$).\n\n:::\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](03_Regression_Review_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=45%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n:::\n\n::: {.fragment}\n\n**As income increases, credit limit tends to increase as well!**\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - In the SLR model between Debt and Income, increases in Income also implies increases in Credit Limit\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - But in the MLR model, **we *fix* Credit Limit, and *then* increase Income independently**\n\n:::\n\n## \"Fixing\" Credit Limit\n\nLet's consider what the model is saying after we \"fix\" credit limit\n\n$$\\widehat{Debt} = -385.179 + 0.264 \\cdot \\textrm{Limit} \\textcolor{red}{- 7.663} \\cdot \\textrm{Income}$$\n\n::: {.fragment .nonincremental}\n\nConsider two people **who have equal Credit Limits**\n\n  - One person has a higher income than the other person\n\n:::\n\n::: {.fragment .nonincremental}\n\n**MLR model:** the person with the higher Income tends to have less Debt\n\n  - **Q:** Why does this make sense?\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - Higher income means they have more resources to pay off their debt!\n\n  - Maybe the reason they have higher income is because they tend to spend less!\n\n  - Higher income may be associated with other factors (e.g., higher education)\n\n:::\n\n## Assumptions, Revisited\n\nIn Multiple Linear Regression, we still must check the LINE Conditions:\n$$\\text{Linearity, Independence, Normality, Equal Variance}$$\n\n::: {.fragment .nonincremental}\n\nThere are two minor differences:\n\n - For independence, we (often) want to avoid models with **\"multicollinearity\"**: some predictors are severely correlated with one another.\n\n:::\n\n::: {.fragment .nonincremental}\n\n - When checking assumptions using residual plots, we must show residuals vs. *predicted values* (instead of $X$).\n\n:::\n\n::: {.fragment .nonincremental}\n\nWhen LINE conditions are met, we can conduct inference just like before!!\n\n  - Same `R` code!\n\n:::\n\n## Hypothesis Test for *all* $\\hat{\\beta}_k$?\n\nWe know how to do hypothesis tests for each *individual* $\\beta_k$...\n$$\nH_0: \\beta_k = 0 \\quad \\quad vs. \\quad \\quad H_A: \\beta_k \\neq 0\n$$\n\n::: {.fragment .nonincremental}\n\nCan we test if **at least one** predictor has a significant linear relationship with the response?\n\n  - **Q:** Why is it \"bad\" to conduct $p$ hypothesis tests (e.g., at 0.05 level)?\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - If $\\beta_1 = \\dots = \\beta_p=0$, then *for each hypothesis test* with $\\alpha=0.05$, there's a 0.05 chance of *falsely* rejecting $H_0: \\beta_k = 0$ (Type I error)\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - Thus, if $\\beta_1 = \\dots = \\beta_p=0$, then the probability of *falsely* determining that *at least one* predictor is statistically significant:\n$$\n  P(\\text{reject at least one false rejection of $H_0$}) = 1 - 0.95^p\n$$\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - e.g., with $p=5$, this is 0.2262\n  - e.g., with $p=14$, this is 0.512\n\n:::\n\n::: {.fragment .nonincremental}\n\n  - Takeaway: We'll often make some mistakes!\n\n:::\n\n## F-Test\n\nIt would be better to do a hypothesis test for *all* $\\beta_k$ *at the same time*:\n$$\nH_0: \\beta_1 = \\dots = \\beta_p = 0 \\quad \\quad H_A: \\text{at least one } \\beta_k\\neq 0\n$$\n\n::: {.nonincremental}\n\n  - Called an **F-Test**.\n\n  - Null sampling distribution follows an \"F-Distribution\"\n\n  - Avoids \"multiple testing\" problem!\n\n:::\n\n## F-Test in `R`\n\n::: {.smaller}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Balance ~ Limit + Income, data = Credit)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-232.79 -115.45  -48.20   53.36  549.77 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -385.17926   19.46480  -19.79   <2e-16 ***\nLimit          0.26432    0.00588   44.95   <2e-16 ***\nIncome        -7.66332    0.38507  -19.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 165.5 on 397 degrees of freedom\nMultiple R-squared:  0.8711,\tAdjusted R-squared:  0.8705 \nF-statistic:  1342 on 2 and 397 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n:::\n\n- Estimated p-value $\\approx 0 \\implies$ strong evidence to reject $H_0$\n\n- Credit Limit or Income (or both) are associated with Debt Balance\n\n# Recap\n\n## Recap\n\n::: {.nonincremental}\n\nToday, we reviewed\n\n  - the linear model and its **assumptions**\n\n  - **coefficient interpretation** in linear regression\n\n  - statistical inference: **confidence intervals** and **hypothesis tests**, including the **F-test**\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}