{
  "hash": "a10f008f6c49d9c27ed04d2d1205c871",
  "result": {
    "engine": "knitr",
    "markdown": "---\npagetitle: \"Linear Regression II\"\neditor: source\nformat:\n  revealjs:\n    html-math-method: mathjax\n    chalkboard: true\n    incremental: true\n    theme: [default, custom.scss]\n    height: 900\n    width: 1600\n    slide-number: c\n    auto-stretch: false\n    callout-appearance: simple\n    pdf-max-pages-per-slide: 2\n    menu:\n      side: right\n      numbers: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n\n::::: columns\n::: {.column .center width=\"55%\"}\n![](img/tidymodels.png){width=\"90%\"}\n:::\n\n::: {.column .center width=\"45%\"}\n<br>\n\n[Linear Regression II]{.custom-title}\n\n<br> <br> <br> <br> <br> \n\n[Grayson White]{.custom-subtitle}\n\n[Stat 243 <br> Week 3 \\| Fall 2026]{.custom-subtitle}\n:::\n:::::\n\n------------------------------------------------------------------------\n\n\n\n## Goals for this week (and next time)\n\n:::: {.columns}\n\n::: {.column width='50%'}\n\n::: {.nonincremental .fragment}\n\n**Today:**\n\n-   Regression diagnostics\n-   Diagnostics activity\n\n:::\n\n:::\n\n::: {.column width='50%'}\n\n::: {.nonincremental .fragment}\n\n**This Week:**\n\n-   More linear regression:\n    - Inference for regression (W)\n    - categorical predictors (W)\n    - multiple linear regression (W)\n    - linear regression extensions (F)\n\n-   Quiz on Lab 1 (F)\n\n\n:::\n\n:::\n\n::::\n\n\n\n\n\n## (Parametric) Statistical Learning\n\n<br><br><br>\n\n$$\ny = f(x) + \\epsilon\n$$\n\n<br><br><br>\n\n**Goal:**\n\n-   Determine a reasonable form for $f()$. (Ex: Line, curve, ...)\n\n-   Estimate $f()$ with $\\hat{f}()$ using the data.\n\n-   Generate predicted values: $\\hat y = \\hat{f}(x)$.\n\n------------------------------------------------------------------------\n\n\n### Simple Linear Regression Model\n\n$$\ny = \\beta_o + \\beta_1 x + \\epsilon\n$$\n\nConsider this model when:\n\n-   Response variable $(y)$: quantitative\n\n-   Explanatory variable $(x)$: quantitative\n\n    -   Have only ONE explanatory variable.\n\n-   AND, $f()$ can be approximated by a line.\n\n-   Need to determine the best **estimates** of $\\beta_o$ and $\\beta_1$.\n\n------------------------------------------------------------------------\n\n#### Distinguishing between the **population** and the **sample**\n\n::::: columns\n::: column\n$$ \ny = \\beta_o + \\beta_1 x + \\epsilon\n$$\n\n::: {.nonincremental}\n\n-   Parameters:\n    -   Based on the **population**\n    -   Unknown then if don't have data on the whole population\n    -   EX: $\\beta_o$ and $\\beta_1$\n    \n:::\n\n\n:::\n\n::: {.column .fragment}\n$$\n\\hat{y} = \\hat{ \\beta}_o + \\hat{\\beta}_1 x\n$$\n\n::: {.nonincremental}\n\n-   Statistics:\n    -   Based on the **sample** data\n    -   Known\n    -   Usually estimate a population parameter\n    -   EX: $\\hat{\\beta}_o$ and $\\hat{\\beta}_1$\n    \n:::\n\n\n:::\n:::::\n\n------------------------------------------------------------------------\n\n### New dataset: [The Ultimate Halloween Candy Power Ranking](https://web.archive.org/web/20200420162003/https://fivethirtyeight.com/videos/the-ultimate-halloween-candy-power-ranking/)\n\n> \"The social contract of Halloween is simple: Provide adequate treats to costumed masses, or be prepared for late-night tricks from those dissatisfied with your offer. To help you avoid that type of vengeance, and to help you make good decisions at the supermarket this weekend, we wanted to figure out what Halloween candy people most prefer. So we devised an experiment: Pit dozens of fun-sized candy varietals against one another, and let the wisdom of the crowd decide which one was best.\" -- Walt Hickey\n\n> \"While we don't know who exactly voted, we do know this: 8,371 different IP addresses voted on about 269,000 randomly generated matchups. So, not a scientific survey or anything, but a good sample of what candy people like.\"\n\n------------------------------------------------------------------------\n\n### Example: [The Ultimate Halloween Candy Power Ranking](https://web.archive.org/web/20200420162003/https://fivethirtyeight.com/videos/the-ultimate-halloween-candy-power-ranking/)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](img/candy_ex.png){fig-align='center' width=80%}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Example: [The Ultimate Halloween Candy Power Ranking](https://web.archive.org/web/20200420162003/https://fivethirtyeight.com/videos/the-ultimate-halloween-candy-power-ranking/)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncandy <- read_csv(\"https://raw.githubusercontent.com/fivethirtyeight/data/master/candy-power-ranking/candy-data.csv\") %>%\n  mutate(pricepercent = pricepercent*100)\n\nglimpse(candy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 85\nColumns: 13\n$ competitorname   <chr> \"100 Grand\", \"3 Musketeers\", \"One dime\", \"One quarter…\n$ chocolate        <dbl> 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…\n$ fruity           <dbl> 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,…\n$ caramel          <dbl> 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ peanutyalmondy   <dbl> 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ nougat           <dbl> 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…\n$ crispedricewafer <dbl> 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ hard             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,…\n$ bar              <dbl> 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…\n$ pluribus         <dbl> 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,…\n$ sugarpercent     <dbl> 0.732, 0.604, 0.011, 0.011, 0.906, 0.465, 0.604, 0.31…\n$ pricepercent     <dbl> 86.0, 51.1, 11.6, 51.1, 51.1, 76.7, 76.7, 51.1, 32.5,…\n$ winpercent       <dbl> 66.97173, 67.60294, 32.26109, 46.11650, 52.34146, 50.…\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n\n\n### New Modeling Goal\n\nNew modeling goal: **predict win percentage by using the price percentage variable**.\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nggplot(data = candy, \n       mapping = aes(x = pricepercent,\n                     y = winpercent)) +\n  geom_point(alpha = 0.6, size = 4, \n             color = \"chocolate4\") +\n  geom_smooth(method = \"lm\", se = FALSE,\n              color = \"deeppink2\")\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n### Constructing the Simple Linear Regression Model in R\n\nWe can use the `lm()` function to construct the simple linear regression model in R. \n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod <- lm(winpercent ~ pricepercent, data = candy)\n\nlibrary(moderndive)\nget_regression_table(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term         estimate std_error statistic p_value lower_ci upper_ci\n  <chr>           <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept      41.979     2.908    14.435   0       36.195   47.763\n2 pricepercent    0.178     0.053     3.352   0.001    0.072    0.283\n```\n\n\n:::\n:::\n\n\n:::\n\n:::{.fragment}\nWhat is the fitted model form? \n:::\n\n:::{.fragment}\n\\begin{align*}\n  \\hat{y} &= \\hat{\\beta_o} + \\hat{\\beta_1} \\times x_{pricepercent} \\\\\n   &= 41.979 + 0.178 \\times x_{pricepercent}\n\\end{align*}\n::: \n\n:::{.fragment}\nHow do we interpret the coefficients?\n:::\n\n\n------------------------------------------------------------------------\n\n### Prediction\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_cases <- data.frame(pricepercent = c(25, 85, 150))\npredict(mod, newdata = new_cases)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1        2        3 \n46.42443 57.09409 68.65289 \n```\n\n\n:::\n:::\n\n\n-   We didn't have any treats in our sample with a price percentage of 85%. Can we still make this prediction?\n    -   Called **interpolation**\n\n<br>\n\n-   We didn't have any treats in our sample with a price percentage of 150%. Can we still make this prediction?\n    -   Called **extrapolation**\n\n------------------------------------------------------------------------\n\n### Cautions\n\n::::: columns\n::: column\n-   Careful to only predict values within the range of $x$ values in the sample.\n\n-   Make sure to investigate **outliers**: observations that fall far from the cloud of points.\n    - High leverage points\n:::\n\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=960}\n:::\n:::\n\n:::\n:::::\n\n\n------------------------------------------------------------------------\n\n### A closer look at our model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nget_regression_table(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 7\n  term         estimate std_error statistic p_value lower_ci upper_ci\n  <chr>           <dbl>     <dbl>     <dbl>   <dbl>    <dbl>    <dbl>\n1 intercept      41.979     2.908    14.435   0       36.195   47.763\n2 pricepercent    0.178     0.053     3.352   0.001    0.072    0.283\n```\n\n\n:::\n:::\n\n\n\n\\begin{align*}\n  \\hat{y} &= \\hat{\\beta_o} + \\hat{\\beta_1} \\times x_{pricepercent} \\\\\n   &= 41.979 + 0.178 \\times x_{pricepercent}\n\\end{align*}\n\n\n:::{.fragment}\nWhat assumptions have we made?\n:::\n\n\n------------------------------------------------------------------------\n\n\n## Linear Regression Assumptions\n\n\nWe can *always* find the line of best fit to explore data, but...\n\n\n:::{.fragment}\n**To make accurate predictions or inferences, certain conditions should be met.**\n:::\n\n\n::: {.fragment}\n\n\\begin{align*}\n\ny &= \\beta_o + \\beta_1 + x + \\epsilon \\\\\n\\epsilon &\\overset{\\mbox{ind}}{\\sim} \\mathcal{N}(0,~ \\sigma^2)\n\n\\end{align*}    \n\n\n:::\n\n\n- Mathematically, all linear regression assumptions are encoded in the above equation. \n\n- However, we can break them down into four easy to remember mnemonics.\n\n\n\n------------------------------------------------------------------------\n\n\n## Linear Regression Assumptions\n\n\n\\begin{align*}\n\ny &= \\beta_o + \\beta_1 + x + \\epsilon \\\\\n\\epsilon &\\overset{\\mbox{ind}}{\\sim} \\mathcal{N}(0,~ \\sigma^2)\n\n\\end{align*}    \n\n\n::: {.nonincremental}\n\n1. **Linearity:** The relationship between explanatory and response variables must be approximately linear\n\n    - Mathematically: $y = \\beta_0 + \\beta_1 x + \\epsilon$ where $\\mathbb{E}(\\epsilon \\ | \\ x) = 0$\n\n    - Check using scatterplot of data, or residual plot\n\n\n:::\n\n\n\n------------------------------------------------------------------------\n\n\n## Linear Regression Assumptions\n\n\n\\begin{align*}\n\ny &= \\beta_o + \\beta_1 + x + \\epsilon \\\\\n\\epsilon &\\overset{\\mbox{ind}}{\\sim} \\mathcal{N}(0,~ \\sigma^2)\n\n\\end{align*}\n\n\n\n::: {.nonincremental}\n\n\n2. **Independence:** The observations should be independent of one another.\n\n    - Mathematically: $\\epsilon_i$ and $\\epsilon_j$ are independent (given $x$)\n    - Can check by considering data context, and\n    - by looking at residual scatterplots too\n\n:::\n\n\n\n\n------------------------------------------------------------------------\n\n\n## Linear Regression Assumptions\n\n\n\\begin{align*}\n\ny &= \\beta_o + \\beta_1 + x + \\epsilon \\\\\n\\epsilon &\\overset{\\mbox{ind}}{\\sim} \\mathcal{N}(0,~ \\sigma^2)\n\n\\end{align*}    \n\n\n::: {.nonincremental}\n\n\n3. **Normality:** The distribution of residuals should be *approximately* bell-shaped, unimodal, symmetric, and centered at 0 at every \"slice\" of the explanatory variable\n\n    - Mathematically: $\\epsilon \\ | \\ x \\sim N(0, \\sigma^2)$\n    - Simple check: look at histogram of residuals\n    - Better to use a \"Q-Q plot\" \n\n\n:::\n\n\n\n------------------------------------------------------------------------\n\n\n## Linear Regression Assumptions\n\n\n\\begin{align*}\n\ny &= \\beta_o + \\beta_1 + x + \\epsilon \\\\\n\\epsilon &\\overset{\\mbox{ind}}{\\sim} \\mathcal{N}(0,~ \\sigma^2)\n\n\\end{align*}    \n\n\n::: {.nonincremental}\n\n\n4. **Equal Variability:** Variance of residuals should be roughly constant across data set. Also called \"homoscedasticity\". Models that violate this assumption are sometimes called \"heteroscedastic\"\n    \n    - Mathematically: $\\mbox{Var}(\\epsilon \\ | \\ x) = \\sigma^2$ for constant $\\sigma^2$\n    - Check using residual plot.\n\n\n:::\n\n\n\n------------------------------------------------------------------------\n\n\n\n\n## A cute way to remember this: **\"LINE\"**\n\n:::{.nonincremental}\n1. **L**inearity: The relationship between explanatory and response variables must be approximately linear\n    \n2. **I**ndependence: The observations should be independent of one another.\n\n3. **N**ormality: The distribution of residuals should be *approximately* bell-shaped, unimodal, symmetric, and centered at 0 at every \"slice\" of the explanatory variable\n\n4. **E**qual Variability: Variance of residuals should be roughly constant across data set. Also called \"homoscedasticity\". Models that violate this assumption are sometimes called \"heteroscedastic\"\n\n:::  \n\n\n## Assessing conditions: diagnostics plots\n\n::::{.columns}\n\n::: {.column width=50%}\n\nIn order to assess if we've met the described conditions, we will utilize four common **diagnostics plots**: \n\n-   Residual vs. fitted plot (i.e. 'residual plot')\n    - for assessing linearity, independence, and equal variability\n-   Normal Q-Q plot\n    - for assessing normality\n-   Residual histogram\n    - for assessing normality\n-   Residual vs. leverage plot\n    - for assessing the influence of outliers \n    \n:::\n\n:::{.column width=5%}\n\n:::\n\n:::{.column width=45%}\n\n:::{.fragment}\n    \nIn order to make these plots, we'll use the `gglm` (grammer of graphics for linear model diagnostics) package.\n\n![](https://raw.githubusercontent.com/graysonwhite/gglm/master/figs/gglm.webp){width=50% fig-align='center'}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Run the below code (without the '#') once\n# install.packages(\"gglm\") \n# Then load with:\nlibrary(gglm)\n```\n:::\n\n\n:::\n\n:::\n\n::::\n\n## Recall out simple linear regression model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod <- lm(winpercent ~ pricepercent, data = candy)\n```\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::{.fragment}\nLet's check if this meets the **LINE** assumptions\n:::\n\n\n## Residual vs. fitted plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(mod) + \n  stat_fitted_resid()\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n-   Linearity: ✅\n\n-   Independence: ✅\n\n-   Equal Variability: ✅\n\n\n## Checking normality: residual histogram\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(mod) + \n  stat_resid_hist(bins = 15)\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n-   Normality: 🤔\n    - Looks pretty good! \n    - We'll look at a Q-Q plot to further assess!\n\n## Checking normality: Q-Q plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(mod) + \n  stat_normal_qq()\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n-   Normality: ✅\n\n\n\n## Checking outliers: Residuals vs. leverage plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(mod) + \n  stat_resid_leverage()\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n-   Looks pretty good! 🤩\n\n\n## Diagnostic shortcut: `gglm::gglm()`\n\n::: {.fragment}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngglm(mod)\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n:::\n\n\n# Now let's simulate some data...\n\n\n## A valid model \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(794)\nn <- 80\nx <- runif(n)\nbeta_1 <- 3.5\nsigma <- .6\ny <- beta_1 * x + rnorm(n, sd = sigma)\ndf <- data.frame(x, y)\nm1 <- lm(y ~ x, data = df)\n```\n:::\n\n\n\n## A valid model\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(df, aes(x = x, y = y)) + \n  geom_point() + \n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## A valid model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngglm(m1)\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## What can break? \n\n\n1. Unbiased estimation of $\\hat\\beta$\n\n2. Accurate assessment of $\\mbox{SE}(\\hat\\beta)$\n    - p-values and hypothesis tests\n    - CIs\n    \n## Checking for breaks \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nit <- 5000\nbeta_hats <- rep(NA, it)\ncapture <- rep(FALSE, it)\nfor(i in 1:it) {\n  y <- beta_1 * x + rnorm(n, sd = sigma)\n  m <- lm(y ~ x)\n  beta_hats[i] <- m$coef[2]\n  ci <- confint(m)[2, ]\n  capture[i] <- (ci[1] < beta_1 & beta_1 < ci[2])\n}\n```\n:::\n\n\n\n## Checking for breaks\n\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nggplot(data.frame(beta_hat = beta_hats), aes(x = beta_hat)) + \n  geom_histogram() + \n  geom_vline(xintercept = beta_1, color = \"tomato\")\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-21-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n::: {.fragment .nonincremental}\n\n- Bias in $\\hat\\beta$'s?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(beta_hats) - beta_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.000283525\n```\n\n\n:::\n:::\n\n\n:::\n\n\n::: {.fragment .nonincremental}\n\n- Accurate assessment of $\\mbox{SE}(\\hat\\beta)$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(capture)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9482\n```\n\n\n:::\n:::\n\n\n:::\n\n\n# Let's break something\n\n\n## Non-constant variance\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(794)\nn <- 80\nx <- runif(n)\ny <- beta_1 * x + rnorm(n, sd = .93 * x)\ndf <- data.frame(x, y)\nm1 <- lm(y ~ x, data = df)\n```\n:::\n\n\n\n## Non-constant variance\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(df, aes(x = x, y = y)) + \n  geom_point() + \n  geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-25-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n## Non-constant variance \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngglm(m1)\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-26-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n\n\n## Checking for breaks \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nit <- 5000\nbeta_hats <- rep(NA, it)\ncapture <- rep(FALSE, it)\nfor(i in 1:it) {\n  y <- beta_1 * x + rnorm(n, sd = .93 * x)\n  m <- lm(y ~ x)\n  beta_hats[i] <- m$coef[2]\n  ci <- confint(m)[2, ]\n  capture[i] <- (ci[1] < beta_1 & beta_1 < ci[2])\n}\n```\n:::\n\n\n\n## Checking for breaks\n\n\n\n::: {.cell layout-align=\"center\" output-location='column'}\n\n```{.r .cell-code}\nggplot(data.frame(beta_hat = beta_hats), \n       aes(x = beta_hat)) + \n  geom_histogram() + \n  geom_vline(xintercept = beta_1, color = \"tomato\")\n```\n\n::: {.cell-output-display}\n![](stat243_wk03mon_files/figure-revealjs/unnamed-chunk-28-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n::: {.fragment .nonincremental}\n\n- Bias in $\\hat\\beta$'s?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(beta_hats) - beta_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.004152782\n```\n\n\n:::\n:::\n\n\n:::\n\n\n::: {.fragment .nonincremental}\n\n- Accurate assessment of $\\mbox{SE}(\\hat\\beta)$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmean(capture)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9106\n```\n\n\n:::\n:::\n\n\n:::\n\n\n## Activity\n\nWith a partner (there needs to be one computer between you), choose one of the following components of the linear model to break, then assess what goes wrong.\n\n\n::: {.nonincremental}\n\n1. Normality of errors\n2. Independence of errors\n3. Linear trend in mean function\n\n:::\n\nYou can build off the code used in these slides.\n\n\n\n## Next time\n\n\n- Inference for regression \n- categorical predictors \n- multiple linear regression \n\n\n\n\n\n",
    "supporting": [
      "stat243_wk03mon_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}